### ISSUE TITLE
countdown disables itself when timeframe set to  Specific day & time

### ISSUE THREAD

**Issue by narimonfund** [WordImpress/Give-Form-Countdown#25] opened 2017-03-02 03:51 UTC
## Issue Overview

When I set the timeframe to  Specific day & time, I click on update, but it does not save the changes. When I check the countdown again, it is disabled.
## Current Behavior

It keeps disabling itself when I set a  Multi-level Donation form to end at a specifc date and time. Looks like it cant save the changes.
## Expected Behavior

to save the changes!
## Possible Solution

If I set the timeframe to end after a number of days,it works just fine. 

I have installed "wp-jalali" (a "Full Jalali (خورشیدی - شمسی) Calendar and Persian(Farsi)/Afghan/Tajik" support package for Wordpress.) It changes the calendar to Persian calendar throughout the website.
However it does not convert the dates from Gregorian calendar to Persian calendar in Give plugin. Instead it basically translates the name of months to Persian. e.g.  03/24/2017 in Persian calendar will be 01/04/1396. 
In the plugin the Gregorian calendar is shown. 

This maybe the cause! 

![image](https://cloud.githubusercontent.com/assets/26129906/23492296/6384a1ea-feb8-11e6-8fc5-1de4563d417b.png)

## Steps to Reproduce (for bugs)

1.Create a multi-level form with 12 levels
2. Set the Timeframe to end at a specific date and time
3. Save the changes
4.It wont work!
## Related PRs
List related PRs against other branches:

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by mathetos** [comment] 2017-03-02 17:19
I don't believe this is a bug quite yet since I cannot reproduce it at all. Let's begin this in our Free Support forum first:
https://wordpress.org/support/plugin/give-form-countdown

Marking as "invalid" at the moment, untill we get more clarity at Support. Thanks!

**Closed by mathetos** 2017-03-02 17:19 UTC

**Comment by mathetos** [comment] 2017-03-02 17:21
I would definitely agree that the Persian calendar is the cause though. Try disabling that first, if the plugin works as expected then the Persian calendar is most definitely the cause.
